lame -b 16 audio/deva_aanth.mp3 audio_lower/deva_aanth.mp3
lame -b 16 audio/deva_ainak.mp3 audio_lower/deva_ainak.mp3
lame -b 16 audio/deva_angoor.mp3 audio_lower/deva_angoor.mp3
lame -b 16 audio/deva_athaara.mp3 audio_lower/deva_athaara.mp3
lame -b 16 audio/deva_aurat.mp3 audio_lower/deva_aurat.mp3
lame -b 16 audio/deva_ba.mp3 audio_lower/deva_ba.mp3
lame -b 16 audio/deva_baais.mp3 audio_lower/deva_baais.mp3
lame -b 16 audio/deva_bakari.mp3 audio_lower/deva_bakari.mp3
lame -b 16 audio/deva_barah.mp3 audio_lower/deva_barah.mp3
lame -b 16 audio/deva_bees.mp3 audio_lower/deva_bees.mp3
lame -b 16 audio/deva_bha.mp3 audio_lower/deva_bha.mp3
lame -b 16 audio/deva_bhalu.mp3 audio_lower/deva_bhalu.mp3
lame -b 16 audio/deva_cha.mp3 audio_lower/deva_cha.mp3
lame -b 16 audio/deva_chaar.mp3 audio_lower/deva_chaar.mp3
lame -b 16 audio/deva_charkha.mp3 audio_lower/deva_charkha.mp3
lame -b 16 audio/deva_chaudah.mp3 audio_lower/deva_chaudah.mp3
lame -b 16 audio/deva_chha.mp3 audio_lower/deva_chha.mp3
lame -b 16 audio/deva_chhatri.mp3 audio_lower/deva_chhatri.mp3
lame -b 16 audio/deva_chhe.mp3 audio_lower/deva_chhe.mp3
lame -b 16 audio/deva_da.mp3 audio_lower/deva_da.mp3
lame -b 16 audio/deva_damaroo.mp3 audio_lower/deva_damaroo.mp3
lame -b 16 audio/deva_das.mp3 audio_lower/deva_das.mp3
lame -b 16 audio/deva_davaat.mp3 audio_lower/deva_davaat.mp3
lame -b 16 audio/deva_dda.mp3 audio_lower/deva_dda.mp3
lame -b 16 audio/deva_ddha.mp3 audio_lower/deva_ddha.mp3
lame -b 16 audio/deva_dha.mp3 audio_lower/deva_dha.mp3
lame -b 16 audio/deva_dhakkan.mp3 audio_lower/deva_dhakkan.mp3
lame -b 16 audio/deva_dhanush.mp3 audio_lower/deva_dhanush.mp3
lame -b 16 audio/deva_dnyandev.mp3 audio_lower/deva_dnyandev.mp3
lame -b 16 audio/deva_do.mp3 audio_lower/deva_do.mp3
lame -b 16 audio/deva_edi.mp3 audio_lower/deva_edi.mp3
lame -b 16 audio/deva_eight.mp3 audio_lower/deva_eight.mp3
lame -b 16 audio/deva_ek.mp3 audio_lower/deva_ek.mp3
lame -b 16 audio/deva_fa.mp3 audio_lower/deva_fa.mp3
lame -b 16 audio/deva_fal.mp3 audio_lower/deva_fal.mp3
lame -b 16 audio/deva_five.mp3 audio_lower/deva_five.mp3
lame -b 16 audio/deva_four.mp3 audio_lower/deva_four.mp3
lame -b 16 audio/deva_ga.mp3 audio_lower/deva_ga.mp3
lame -b 16 audio/deva_gaay.mp3 audio_lower/deva_gaay.mp3
lame -b 16 audio/deva_gha.mp3 audio_lower/deva_gha.mp3
lame -b 16 audio/deva_ghadi.mp3 audio_lower/deva_ghadi.mp3
lame -b 16 audio/deva_gyarah.mp3 audio_lower/deva_gyarah.mp3
lame -b 16 audio/deva_ha.mp3 audio_lower/deva_ha.mp3
lame -b 16 audio/deva_hal.mp3 audio_lower/deva_hal.mp3
lame -b 16 audio/deva_hr.mp3 audio_lower/deva_hr.mp3
lame -b 16 audio/deva_iishvar.mp3 audio_lower/deva_iishvar.mp3
lame -b 16 audio/deva_ikkis.mp3 audio_lower/deva_ikkis.mp3
lame -b 16 audio/deva_imli.mp3 audio_lower/deva_imli.mp3
lame -b 16 audio/deva_ja.mp3 audio_lower/deva_ja.mp3
lame -b 16 audio/deva_jahaj.mp3 audio_lower/deva_jahaj.mp3
lame -b 16 audio/deva_jha.mp3 audio_lower/deva_jha.mp3
lame -b 16 audio/deva_jnya.mp3 audio_lower/deva_jnya.mp3
lame -b 16 audio/deva_ka.mp3 audio_lower/deva_ka.mp3
lame -b 16 audio/deva_kabutar.mp3 audio_lower/deva_kabutar.mp3
lame -b 16 audio/deva_kha.mp3 audio_lower/deva_kha.mp3
lame -b 16 audio/deva_khargosh.mp3 audio_lower/deva_khargosh.mp3
lame -b 16 audio/deva_ksha.mp3 audio_lower/deva_ksha.mp3
lame -b 16 audio/deva_kshatriya.mp3 audio_lower/deva_kshatriya.mp3
lame -b 16 audio/deva_la.mp3 audio_lower/deva_la.mp3
lame -b 16 audio/deva_lattu.mp3 audio_lower/deva_lattu.mp3
lame -b 16 audio/deva_letter_a.mp3 audio_lower/deva_letter_a.mp3
lame -b 16 audio/deva_letter_aa.mp3 audio_lower/deva_letter_aa.mp3
lame -b 16 audio/deva_letter_aha.mp3 audio_lower/deva_letter_aha.mp3
lame -b 16 audio/deva_letter_ai.mp3 audio_lower/deva_letter_ai.mp3
lame -b 16 audio/deva_letter_anuswar.mp3 audio_lower/deva_letter_anuswar.mp3
lame -b 16 audio/deva_letter_au.mp3 audio_lower/deva_letter_au.mp3
lame -b 16 audio/deva_letter_candra_a.mp3 audio_lower/deva_letter_candra_a.mp3
lame -b 16 audio/deva_letter_candra_o.mp3 audio_lower/deva_letter_candra_o.mp3
lame -b 16 audio/deva_letter_e.mp3 audio_lower/deva_letter_e.mp3
lame -b 16 audio/deva_letter_i.mp3 audio_lower/deva_letter_i.mp3
lame -b 16 audio/deva_letter_ii.mp3 audio_lower/deva_letter_ii.mp3
lame -b 16 audio/deva_letter_o.mp3 audio_lower/deva_letter_o.mp3
lame -b 16 audio/deva_letter_om.mp3 audio_lower/deva_letter_om.mp3
lame -b 16 audio/deva_letter_u.mp3 audio_lower/deva_letter_u.mp3
lame -b 16 audio/deva_letter_uu.mp3 audio_lower/deva_letter_uu.mp3
lame -b 16 audio/deva_letter_vocalic_r.mp3 audio_lower/deva_letter_vocalic_r.mp3
lame -b 16 audio/deva_lla.mp3 audio_lower/deva_lla.mp3
lame -b 16 audio/deva_ma.mp3 audio_lower/deva_ma.mp3
lame -b 16 audio/deva_machhali.mp3 audio_lower/deva_machhali.mp3
lame -b 16 audio/deva_na.mp3 audio_lower/deva_na.mp3
lame -b 16 audio/deva_nal.mp3 audio_lower/deva_nal.mp3
lame -b 16 audio/deva_nau.mp3 audio_lower/deva_nau.mp3
lame -b 16 audio/deva_nga.mp3 audio_lower/deva_nga.mp3
lame -b 16 audio/deva_nine.mp3 audio_lower/deva_nine.mp3
lame -b 16 audio/deva_nna.mp3 audio_lower/deva_nna.mp3
lame -b 16 audio/deva_nnna.mp3 audio_lower/deva_nnna.mp3
lame -b 16 audio/deva_nya.mp3 audio_lower/deva_nya.mp3
lame -b 16 audio/deva_okhali.mp3 audio_lower/deva_okhali.mp3
lame -b 16 audio/deva_one.mp3 audio_lower/deva_one.mp3
lame -b 16 audio/deva_pa.mp3 audio_lower/deva_pa.mp3
lame -b 16 audio/deva_paanch.mp3 audio_lower/deva_paanch.mp3
lame -b 16 audio/deva_pandrah.mp3 audio_lower/deva_pandrah.mp3
lame -b 16 audio/deva_patang.mp3 audio_lower/deva_patang.mp3
lame -b 16 audio/deva_pha.mp3 audio_lower/deva_pha.mp3
lame -b 16 audio/deva_ra.mp3 audio_lower/deva_ra.mp3
lame -b 16 audio/deva_rath.mp3 audio_lower/deva_rath.mp3
lame -b 16 audio/deva_rishi.mp3 audio_lower/deva_rishi.mp3
lame -b 16 audio/deva_sa.mp3 audio_lower/deva_sa.mp3
lame -b 16 audio/deva_saant.mp3 audio_lower/deva_saant.mp3
lame -b 16 audio/deva_sapera.mp3 audio_lower/deva_sapera.mp3
lame -b 16 audio/deva_sataara.mp3 audio_lower/deva_sataara.mp3
lame -b 16 audio/deva_seven.mp3 audio_lower/deva_seven.mp3
lame -b 16 audio/deva_sha.mp3 audio_lower/deva_sha.mp3
lame -b 16 audio/deva_shalgam.mp3 audio_lower/deva_shalgam.mp3
lame -b 16 audio/deva_shatkoan.mp3 audio_lower/deva_shatkoan.mp3
lame -b 16 audio/deva_shr.mp3 audio_lower/deva_shr.mp3
lame -b 16 audio/deva_sign_chandrabindu.mp3 audio_lower/deva_sign_chandrabindu.mp3
lame -b 16 audio/deva_six.mp3 audio_lower/deva_six.mp3
lame -b 16 audio/deva_solah.mp3 audio_lower/deva_solah.mp3
lame -b 16 audio/deva_ssha.mp3 audio_lower/deva_ssha.mp3
lame -b 16 audio/deva_ta.mp3 audio_lower/deva_ta.mp3
lame -b 16 audio/deva_talwaar.mp3 audio_lower/deva_talwaar.mp3
lame -b 16 audio/deva_tamatar.mp3 audio_lower/deva_tamatar.mp3
lame -b 16 audio/deva_tarbooj.mp3 audio_lower/deva_tarbooj.mp3
lame -b 16 audio/deva_teen.mp3 audio_lower/deva_teen.mp3
lame -b 16 audio/deva_terah.mp3 audio_lower/deva_terah.mp3
lame -b 16 audio/deva_tha.mp3 audio_lower/deva_tha.mp3
lame -b 16 audio/deva_tharmas.mp3 audio_lower/deva_tharmas.mp3
lame -b 16 audio/deva_thathera.mp3 audio_lower/deva_thathera.mp3
lame -b 16 audio/deva_three.mp3 audio_lower/deva_three.mp3
lame -b 16 audio/deva_trishul.mp3 audio_lower/deva_trishul.mp3
lame -b 16 audio/deva_tta.mp3 audio_lower/deva_tta.mp3
lame -b 16 audio/deva_ttha.mp3 audio_lower/deva_ttha.mp3
lame -b 16 audio/deva_two.mp3 audio_lower/deva_two.mp3
lame -b 16 audio/deva_ullu.mp3 audio_lower/deva_ullu.mp3
lame -b 16 audio/deva_unnis.mp3 audio_lower/deva_unnis.mp3
lame -b 16 audio/deva_uunt.mp3 audio_lower/deva_uunt.mp3
lame -b 16 audio/deva_va.mp3 audio_lower/deva_va.mp3
lame -b 16 audio/deva_vajan.mp3 audio_lower/deva_vajan.mp3
lame -b 16 audio/deva_virama_halanta.mp3 audio_lower/deva_virama_halanta.mp3
lame -b 16 audio/deva_vowel_a.mp3 audio_lower/deva_vowel_a.mp3
lame -b 16 audio/deva_vowel_aa.mp3 audio_lower/deva_vowel_aa.mp3
lame -b 16 audio/deva_vowel_ai.mp3 audio_lower/deva_vowel_ai.mp3
lame -b 16 audio/deva_vowel_anuswar.mp3 audio_lower/deva_vowel_anuswar.mp3
lame -b 16 audio/deva_vowel_au.mp3 audio_lower/deva_vowel_au.mp3
lame -b 16 audio/deva_vowel_candra_e.mp3 audio_lower/deva_vowel_candra_e.mp3
lame -b 16 audio/deva_vowel_candra_o.mp3 audio_lower/deva_vowel_candra_o.mp3
lame -b 16 audio/deva_vowel_e.mp3 audio_lower/deva_vowel_e.mp3
lame -b 16 audio/deva_vowel_high_dot.mp3 audio_lower/deva_vowel_high_dot.mp3
lame -b 16 audio/deva_vowel_i.mp3 audio_lower/deva_vowel_i.mp3
lame -b 16 audio/deva_vowel_ii.mp3 audio_lower/deva_vowel_ii.mp3
lame -b 16 audio/deva_vowel_o.mp3 audio_lower/deva_vowel_o.mp3
lame -b 16 audio/deva_vowel_u.mp3 audio_lower/deva_vowel_u.mp3
lame -b 16 audio/deva_vowel_uu.mp3 audio_lower/deva_vowel_uu.mp3
lame -b 16 audio/deva_vowel_visarga.mp3 audio_lower/deva_vowel_visarga.mp3
lame -b 16 audio/deva_vowel_vocalic_r.mp3 audio_lower/deva_vowel_vocalic_r.mp3
lame -b 16 audio/deva_ya.mp3 audio_lower/deva_ya.mp3
lame -b 16 audio/deva_yagya.mp3 audio_lower/deva_yagya.mp3
lame -b 16 audio/deva_za.mp3 audio_lower/deva_za.mp3
lame -b 16 audio/deva_zanda.mp3 audio_lower/deva_zanda.mp3
lame -b 16 audio/deva_zero.mp3 audio_lower/deva_zero.mp3
